name: 'ad_reporting'
version: '0.7.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  ad_reporting__pinterest_enabled: true
  ad_reporting__microsoft_ads_enabled: false
  ad_reporting__linkedin_ads_enabled: false
  ad_reporting__google_ads_enabled: true
  ad_reporting__twitter_ads_enabled: false
  ad_reporting__facebook_ads_enabled: true
  ad_reporting__snapchat_ads_enabled: false
  ad_reporting__tiktok_ads_enabled: false

models:
  ad_reporting:
    +materialized: table
  
  pinterest:
    enabled: true
  pinterest_source:
    enabled: true
  
  microsoft_ads:
    enabled: false
  microsoft_ads_source:
    enabled: false
  
  linkedin:
    enabled: false
  linkedin_source:
    enabled: false
  
  twitter_ads:
    enabled: false
  twitter_ads_source:
    enabled: false
  
  facebook_ads:
    enabled: true
  facebook_ads_source:
    enabled: true
  facebook_ads_creative_history:
    enabled: true
  
  google_ads:
    enabled: true
  google_ads_source:
    enabled: true

  snapchat_ads:
    enabled: false
  snapchat_ads_source:
    enabled: false

  tiktok_ads:
    enabled: true
  tiktok_ads_source:
    enabled: true
